In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings 

warnings.filterwarnings("ignore")

%matplotlib inline

In [4]:
df=pd.read_csv(r"cardekho_imputated.csv",index_col=[0])

In [5]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

### Data cleaning

#### Handling Missing Values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.6+ MB

In [7]:
### checking for the missong values
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [8]:
### removing the unecessry columns 
df.drop('car_name',axis=1,inplace=True)
df.drop('brand',axis=1,inplace=True)

In [9]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [10]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [11]:
### getting the numerical features 
num_features=[feature for feature in df.columns if df[feature].dtype !='O']
print("num of the numerical features are:",len(num_features))
cat_features=[feature for feature in df.columns if df[feature].dtype=='O']
print("num of the caegorical features is",len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique()) <=25]
print("num of the discrete features are:",len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print("num of the continuous feature is",len(continuous_features))

num of the numerical features are: 7
num of the caegorical features is 4
num of the discrete features are: 2
num of the continuous feature is 5

In [12]:
### indepent and dependent features
from sklearn.model_selection import train_test_split
x=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [13]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [14]:
y.head()

0    120000
1    550000
2    215000
3    226000
4    570000
Name: selling_price, dtype: int64

### Feature Encoding and Scaling

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['model']=le.fit_transform(x['model'])

In [16]:
x['model']

0          7
1         54
2        118
3          7
4         38
        ...
19537    117
19540     42
19541     77
19542    114
19543     25
Name: model, Length: 15411, dtype: int64

In [17]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [22]:
### creating the column trandformer with three types of transformers
num_features=x.select_dtypes(exclude="object").columns
onehot_columns=['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,onehot_columns),
        ("StandardScaler",numeric_transformer,num_features)
    ],remainder="passthrough"
)

In [25]:
x

array([[ 1.        ,  0.        ,  0.        , ..., -1.32425883,
        -1.26335238, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43257082, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  1.32979434,
         0.91715831,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ...,  0.02099878,
         0.39588361, -0.40302241]], shape=(15411, 14))

In [26]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [46]:
### train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=35)

In [47]:
x_train

array([[ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.50471152, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.93469065,
        -0.7816387 , -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06217472,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ..., -0.21696405,
        -0.16029788,  2.07344426]], shape=(12328, 14))

### Model Training and Model selection

In [48]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [50]:
### create a function to evaluate model
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted)
    return mae,rmse,r2_square

In [62]:
### begining of the model training 
models={
    "Linear Regression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random Forest Regressor":RandomForestRegressor(), 
    
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    ## make predictions
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)
    
    ## evaluate train and test dataset
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    
    print('model performance for training set')
    print("-Root mean squarred error :{:.4f}".format(model_train_rmse))
    print("-Mean Absoulte eror:{:.4f}".format(model_train_mae))
    print("-r2 score:{:.4f}".format(model_train_r2))
    
    print("-------------------------------------------------------")
    
    print('model performance for test  set')
    print("-Root mean squarred error :{:.4f}".format(model_test_rmse))
    print("-Mean Absoulte eror:{:.4f}".format(model_test_mae))
    print("-r2 score:{:.4f}".format(model_test_r2))
    
    
    print('=*35')
    print('\n')

Linear Regression
model performance for training set
-Root mean squarred error :555750.2325
-Mean Absoulte eror:270587.3304
-r2 score:0.6209
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :492712.3332
-Mean Absoulte eror:280592.2729
-r2 score:0.6711
=*35


Lasso
model performance for training set
-Root mean squarred error :555750.2361
-Mean Absoulte eror:270585.2439
-r2 score:0.6209
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :492711.9100
-Mean Absoulte eror:280590.0740
-r2 score:0.6711
=*35


Ridge
model performance for training set
-Root mean squarred error :555750.7668
-Mean Absoulte eror:270553.6432
-r2 score:0.6209
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :492696.4770
-Mean Absoulte eror:280541.7473
-r2 score:0.6711
=*35


K-Neighbors Regressor
model performance for training set
-Root mean squarred error :307389.1009
-Mean Absoulte eror:89442.1054
-r2 score:0.8840
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :346184.8547
-Mean Absoulte eror:116263.7609
-r2 score:0.8376
=*35


Decision Tree
model performance for training set
-Root mean squarred error :19054.4255
-Mean Absoulte eror:4792.8374
-r2 score:0.9996
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :817812.5152
-Mean Absoulte eror:144144.7832
-r2 score:0.0938
=*35


Random Forest Regressor
model performance for training set
-Root mean squarred error :123203.4136
-Mean Absoulte eror:39445.4026
-r2 score:0.9814
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :409725.7953
-Mean Absoulte eror:105943.2813
-r2 score:0.7725
=*35

### Hyperparameter tunning

In [63]:
knn_params={"n_neighbors":[2,3,10,20,40,50]}
rf_params={
    "max_depth":[5,8,15,None,10],
    "max_features":[5,7,"auto",8],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[100,200,500,1000]
    
}

In [64]:
## models list for the hyperparameter tunning
randomcv_models=[('KNN',KNeighborsRegressor(),knn_params),
                 ("RF",RandomForestRegressor(),rf_params)]

In [69]:
from sklearn.model_selection import RandomizedSearchCV

model_param={}

for name,model,params in randomcv_models:
    random=RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=100,
        cv=3,
        verbose=2,
        n_jobs=-1
        
    )
    
    random.fit(x_train,y_train)
    model_param[name]=random.best_params_
    
for model_name in model_param:
    print(f"-----------------Best params for {model_name}----------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
-----------------Best params for KNN----------------------
{'n_neighbors': 2}
-----------------Best params for RF----------------------
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 7, 'max_depth': 15}

In [72]:
### retaining models with best parametrs 
models={
    "K-Neighbors Regressor":KNeighborsRegressor(n_neighbors=2,n_jobs=-1),
    "Random Forest Regressor":RandomForestRegressor(n_estimators=100,min_samples_split=2,max_features=7,max_depth=15),
    
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    ## make predictions
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)
    
    ## evaluate train and test dataset
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    
    print('model performance for training set')
    print("-Root mean squarred error :{:.4f}".format(model_train_rmse))
    print("-Mean Absoulte eror:{:.4f}".format(model_train_mae))
    print("-r2 score:{:.4f}".format(model_train_r2))
    
    print("-------------------------------------------------------")
    
    print('model performance for test  set')
    print("-Root mean squarred error :{:.4f}".format(model_test_rmse))
    print("-Mean Absoulte eror:{:.4f}".format(model_test_mae))
    print("-r2 score:{:.4f}".format(model_test_r2))
    
    
    print('=*35')
    print('\n')

K-Neighbors Regressor
model performance for training set
-Root mean squarred error :209877.5180
-Mean Absoulte eror:63120.5741
-r2 score:0.9459
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :333622.4171
-Mean Absoulte eror:116912.9095
-r2 score:0.8492
=*35


Random Forest Regressor
model performance for training set
-Root mean squarred error :124010.7652
-Mean Absoulte eror:54319.7926
-r2 score:0.9811
-------------------------------------------------------
model performance for test  set
-Root mean squarred error :249470.5972
-Mean Absoulte eror:98530.1459
-r2 score:0.9157
=*35